### ISSUE TITLE
Fixing axis range in ggspider

### ISSUE THREAD

**Issue by TMalta** [Ringomed/ggvanced#1]
Hi @Ringomed 

Thank you very much for this awesome package you developed. The ggspider function is helping me a lot. 
I have a question. How do I fix the range of the axis to be from 0 to 100 and not to take the the max and minimum of each variable (column)? Something like what is below, where I added to rows with values fixed at 0 and 100.
<img width="428" alt="Screenshot 2023-09-04 152606" src="https://github.com/Ringomed/ggvanced/assets/8023683/3a30be14-53a5-4a43-9536-f616b4447aff">
Is this possible in your function?
Cheers,
Tiago

**Comment by TMalta** [comment]
Thank you @Ringomed for your quick response. I always tell my students to read the description of the functions and failed to do it myself. It worked perfectly. 
Again, thank you for building this package. It is great.

Cheers

**Comment by Ringomed** [comment]
I'm glad the problem is solved. I'll update the vignette with an example to make it clearer what the subset argument is for :)
