### ISSUE TITLE
Add option for flipping selected axes?

### ISSUE THREAD

**Issue by veggabo** [Ringomed/ggvanced#4]
Thanks for a very useful package!

Is it possible to add an option for flipping selected variable scales in the `ggspider()` function? 

**An example:** The y-axis for variable 1 _increase_ from the center, while the y-axis for variable 2 _decrease_ from the center. 

For an attempt on illustrating what I'm thinking, I have provided a screenshot of my resulting figure, where the direction of the arrows illustrate the way I want the respective variable axes to increase. So, REN Share should have the value 6.87 on the most outer ring, and 68.44 on the ring closest to the center. 

![yi0Uw2hF8q](https://github.com/Ringomed/ggvanced/assets/47369762/03b62322-5ba5-4f8b-b181-25d08b97f755)

**Comment by Ringomed** [comment]
Hi, @veggabo,

I think I understand what you want,
I will try to implement the requested feature when I find some spare time next week.

Best,
Zvonimir

**Comment by Ringomed** [comment]
Hi, @veggabo,

I have implemented the requested feature through the reorder_axis argument. Please cheack out the new feature, so I can close the issue if you notice no odd beahaviours.

Best,
Zvonimir ;)

**Comment by veggabo** [comment]
Hi @Ringomed ,

Wonderful, it works just as I want! Again, many thanks for a great package, and a very positive and quick response!
